---
- name: Core/Base Install for Arch/Artix
  hosts: all
  become: yes

  tasks:

# Core Applications and Basics
  # - name: The Nucleus
  #   ansible.builtin.user:
  #     name: "hacky"
  #     comment: "hacky"
  #     # groups:
  #     #   - networkmanager
  #     #   - wheel
  #     #   - plugdev
  #     #   - dialout
  #     #   - libvirtd
  #     state: present
  #   become: true

# Github 
  - name: Git Config Username
    community.general.git_config:
      name: "Jon"
      scope: global
    
# Create the AUR User
  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

# Install Packages from Base
  - name: Install Base Arch Pkgs
    pacman:
      update_cache: yes
      name:
        - audacious
        - cups
        - cups-pdf
        - curl
        - delve
        - eza
        - fastfetch
        - fish
        - gnome-browser-connector
        - gnome-tweaks
        - go
        - grub-btrfs
        - helix
        - hydra
        - john
        - kitty
        - libreoffice-still
        - lldb
        - marksman
        - mpv
        - nmap
        - net-tools
        - openssh
        - openvpn
        - putty
        - qbittorrent
        - remmina
        - ripgrep
        - ruff
        - signal-desktop
        - snapper
        - speedtest-cli
        - starship
        - stow
        - timeshift
        - wget
        - yt-dlp
        - wezterm
        - wireshark-qt
        - yazi
        - zellij

# Install packages from the AUR
  - name: Install AUR pkgs
    become: true
    become_user: aur_builder
    kewlfft.aur.aur:
      use: yay
      name:
        - brave-bin
        - brlaser-git
        - catppuccin-gtk-theme-mocha
        - ffuf-bin
        - gobuster-bin
        - golangci-lint-langserver-bin
        - markdown-oxide-git
        - microsoft-edge-stable-bin
        - simplex-desktop-appimage
        - synology-drive
        - ttf-firacode
        - ttf-firacode-nerd
        - ttf-iosevka
        - ttf-iosevka-aile
      state: present

# Change Shell
  - name: Change to FISH Shell
    become: yes
    user:
      name: "hacky"
      shell: /bin/fish
