---
- name: playbook_core.yml - archlinux base setup
  hosts: all
  become: yes

  tasks:

# Update Arch
    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

# Create the AUR User
    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644

# Install Pkgs
    - name: Install Base Arch Pkgs
      pacman:
        update_cache: yes
        name:
          - ansible-language-server
          - btop
          - cups
          - cups-pdf
          - curl
          - delve
          - dosfstools
          - eza
          - fastfetch
          - fish
          - fragments
          - freerdp
          - go
          - gopls
          - grub-btrfs
          - helix
          - hydra
          - john
          - kitty
          - libreoffice-still
          - lldb
          - marksman
          - mpv
          - net-tools
          - nix
          - nmap        
          - ntfs-3g
          - openssh
          - openvpn
          - pyright
          - python
          - python-lsp-server
          - python-pexpect
          - putty
          - remmina
          - ripgrep
          - rhythmbox
          - ruff
          - rust
          - rust-analyzer
          - screen
          - signal-desktop
          - speedtest-cli
          - starship
          - stow
          - tailscale
          - timeshift
          - tldr
          - unzip
          - vscode-json-languageserver
          - wget
          - yaml-language-server
          - yt-dlp
          - wireshark-qt
          - yazi
          - zellij

# Install packages from the AUR
    - name: Install AUR pkgs
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        name:
          - banana-cursor-bin
          - brave-bin
          - brlaser
          - ffuf-bin
          - gnome-shell-extension-appindicator-git
          - gnome-shell-extension-wallpaper-slideshow
          - gobuster-bin
          - golangci-lint
          - golangci-lint-langserver-bin
          - microsoft-edge-stable-bin
          - ppd-toshiba-estudio5560c
          - simplex-desktop-appimage
          - sshs-bin
          - synology-drive
          - timeshift-autosnap
          - ttf-firacode
          - ttf-firacode-nerd
          - ttf-iosevka
          - ttf-iosevka-aile
          - vscode-css-languageserver
          - vscode-html-languageserver
        state: present

# Change Shell
    - name: Change to FISH Shell
      become: yes
      user:
        name: "hacky"
        shell: /bin/fish

# SSH
    - name: SSH
      pacman:
        name:
          - openssh

    - name: enable and start ssh
      systemd:
        name: sshd
        enabled: yes
        state: started
