---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  changed_when: false

- name: Install AUR Packages
  ansible.builtin.import_tasks: aur.yml  
